# Generated by Django 6.0.5 on 2026-08-18 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(choices=[('mind', 'Mind'), ('heart', 'Heart'), ('family', 'Family'), ('teen', 'Teen'), ('grief', 'Grief'), ('stress', 'Stress'), ('trauma', 'Trauma'), ('mindfulness', 'Mindfulness'), ('career', 'Career'), ('group', 'Group')], default='mind', max_length=20)),
                ('session_type', models.CharField(choices=[('individual', 'Individual'), ('couples', 'Couples'), ('family', 'Family'), ('group', 'Group')], default='individual', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.PositiveIntegerField(help_text='Session length in minutes')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('mode', models.CharField(choices=[('in_person', 'In Person'), ('virtual', 'Virtual (Video Call)')], default='in_person', max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.service')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
    ]
